version: '3.1'

services:

  mongo-dmsn:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /Users/telaak/Documents/dmsn-mongo/:/data/db

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      MONGO_ADDRESS: mongo-dmsn
      COOKIE_SECRET: taalasmaa
      DOMAIN: laaksonen.eu
      SENDGRID_API_KEY: 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
      GSMTTY: /dev/ttyUSB0
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0